### ISSUE TITLE
Change heading text color to white

### ISSUE THREAD

**Issue by syswhiz-admin** [syswhiz/Syswhiz#2]
Change heading text color to white and keep everything else as it is. Currently it is linked to the theme color that is linked to button color, so changing it to white changes buttons to white, and text color of button is already white, so all users see is a white ractangle.

**Comment by syswhiz-admin** [comment]
Informed customer - I can set custom color (white) for header, if you want. But its a manual change, if I make that change, it will be difficult for you to change custom color (white) for header.

Customer is ok with the change.

**Comment by Brown-Ninja** [comment]
Following dditional CSS has been added

.site-description {
color: #FFF;
}

.site-header {
background-color: rgba(42, 164, 234, 0.8);
}

.site-header-layout-one .main-navigation {
background-color: rgba(42, 164, 234, 0.8);
}

.site-footer-bottom-bar{
background-color: rgba(42, 164, 234, 0.8);
color: #FFF;
}

.main-navigation ul ul {
background-color: rgba(42, 164, 234, 0.9);
box-shadow: 0 2px 5px rgba(42, 164, 234, 0.12);
}

.site-title a {
color: #FFF;
}
