### ISSUE TITLE
Removing items from cart

### ISSUE THREAD

**Issue by sudsys4u** [syswhiz/Syswhiz#4]
Hey! When you add an item to cart, and while in the Shop, you select the red X in the cart,  to the right of the Shop, it does not remove the item.
I have tried going to cart and removing from there and it says it has been removed.  So I went back to the shop, put something else in the cart and it showed the new item in addition to the other item I removed.

Bottom line, removing items from cart isn't working right.

Thanks - Denise

**Comment by Brown-Ninja** [comment]
Verified the problem. Once you are inside a cart, it takes 2-3 clicks to delete an item!

**Comment by Brown-Ninja** [comment]
Page cache was causing this issue. I added /cart/ page as an exception to the to plugin for cache. It should work well now. 

@sudsys4u  Please clear your browser history and test the results.  Let me know if this issue is not fixed. I will reopen it.

**Comment by Brown-Ninja** [comment]
cache plugin - added option to not to cache any page from this website.
