### ISSUE TITLE
How to change the price of an item

### ISSUE THREAD

**Issue by sudsys4u** [syswhiz/Syswhiz#5]
Hey, Cannot figure out how to change the price of an item.

Can you send notes, please?

Thanks! Denise

**Comment by Brown-Ninja** [comment]
Checkout this link: http://www.inmotionhosting.com/support/edu/woocommerce/how-to-change-product-prices-in-woocommerce
[How to Change Product Prices in WooCommerce - InMotion Hosting.pdf](https://github.com/syswhiz/Syswhiz/files/921250/How.to.Change.Product.Prices.in.WooCommerce.-.InMotion.Hosting.pdf)

**Comment by Brown-Ninja** [comment]
Let me know if you are still having any issue.

**Comment by sudsys4u** [comment]
That was it! Thanks!
