### ISSUE TITLE
Word, 'Shop' no longer white, while viewing an item

### ISSUE THREAD

**Issue by sudsys4u** [syswhiz/Syswhiz#6]
When shopping and viewing an item, the word 'Shop' in the menu is no longer in white. It turns Blue.  For some non savvy computer people, I think this will be confusing. Can we get this to stay White?
Thanks - Denise

**Comment by sudsys4u** [comment]
This actually happens for each menu item, when you are under that menu.

**Comment by Brown-Ninja** [comment]
`/*
You can add your own CSS here.

Click the help icon above to learn more.
*/


.site-description {
    color: #FFF;
}

.site-header {
  background-color: rgba(42, 164, 234, 0.8);
}

.site-header-layout-one .main-navigation {
    background-color: rgba(42, 164, 234, 0.8);
}

.site-footer-bottom-bar{
	 background-color: rgba(42, 164, 234, 0.8);
	color: #FFF;
}

.main-navigation ul ul {
    background-color: rgba(42, 164, 234,  0.9);
    box-shadow: 0 2px 5px rgba(42, 164, 234, 0.12);
}

.site-title a {
color: #FFF;
}

a:hover{
	color: #f2edea;
}

.main-navigation div > ul > li > a:hover{
	color: #f2edea;
}`

Last three CSS fixes this issue
