### ISSUE TITLE
How do you change image under 'About Us' section?

### ISSUE THREAD

**Issue by sudsys4u** [syswhiz/Syswhiz#8]
I need assistance changing the image displayed in the 'About Us' section.

**Comment by Brown-Ninja** [comment]
[How to change text and image on pages.pdf](https://github.com/syswhiz/Syswhiz/files/921258/How.to.change.text.and.image.on.pages.pdf)

**Comment by Brown-Ninja** [comment]
Try he link above. It should help. Let me know, if it does not.

**Comment by sudsys4u** [comment]
That did it! Thanks!
